### ISSUE TITLE
Q1: Palindromes

### ISSUE THREAD

**Issue by tchamberlin** [GreenBankObservatory/summer_onboarding_2024#2]
# Palindromes

## 1.1: is_palindrome function

Write a Python function that detects [palindromes](https://en.wikipedia.org/wiki/Palindrome). Save your script as `ispal.py`. Test your script via `$ python ispal.py`. Add your script to your git repository and make a commit

```py
def is_palindrome(string):
    """Determines whether input `string` is a palindrome"""

    # Your implementation here:
    ...


tests = [
    ("askdfjs", False),
    ("racecar", True),
    ("RaceCar", True),
    ("palindrome", False),
    ("1234321", True),
    ("⭐📡👀", False),
    ("🌿🌼🌿", True),
]


def test_is_palindrome():
    failures = []
    for string, expected_result in tests:
        actual_result = is_palindrome(string)
        if actual_result != expected_result:
            failures.append(
                f"Expected is_palindrome({string!r}) to return "
                f"{expected_result}; got {actual_result}"
            )

    if failures:
        fstr = "\n".join(failures)
        raise AssertionError(f"Your function failed with the following inputs:\n{fstr}")
    else:
        print("Success!")


if __name__ == "__main__":
    test_is_palindrome()

```

## 1.2: ispal CLI

Create a command line interface for your script using `argparse`. Your CLI should accept a single argument: the input string that you are testing for palindromeness.

Your script should print "True" and exit with code `0` if the input string is a palindrome. If the input string is *not* a palindrome, it should print "False" and exit with code `1`

You should be able to reproduce the following output with your script. 

```bash
$ python ispal.py racecar; echo $?
True
0

$ python ispal.py RaceCar; echo $?
True
0

$ python ispal.py 🌿🌼🌿; echo $?
True
0

$ python ispal.py askdfjs; echo $?
False
1
```

Once complete, you will need to commit your script to this repo (`summer_onboarding_2024`), and push your commit to origin

**Comment by sofiarobertson** [comment]
string = string.lower()
    return string == string[::-1]

**Comment by tchamberlin** [comment]
Completed via 075ef2e10ae822312c9869dade28f3021bff3b79

**Comment by tchamberlin** [comment]
Reopened pending completion of 1.2

**Comment by tchamberlin** [comment]
Could you include some example output from your `ispal.py` CLI here?

**Comment by sofiarobertson** [comment]
>> $ python ispal.py Level; echo $?
True
0

>> $ python ispal.py Palindrome; echo $?
False
1

(given outputs worked as well)
