### ISSUE TITLE
Create 10,000 Questions in your database, each with 1-10 Choices

### ISSUE THREAD

**Issue by tchamberlin** [GreenBankObservatory/summer_onboarding_2024#5]
Questions and Choices should have random but English-looking text

Use the `faker` library to generate this fake text

https://github.com/joke2k/faker

`pip install faker`

Each choice should have between 0 and 5 votes

**Comment by tchamberlin** [comment]
Learning about `faker` isn't the primary goal of this, so here's some code to get you started

```py
from faker import Faker
fake = Faker()

question_text = f"{fake.text(30)[:-1]}?"
choice_text = fake.text(20)
```

**Comment by tchamberlin** [comment]
I suggest approaching this iteratively. Start by experimenting in the shell, trying to build some code that will create arbitrary numbers of Questions and Choices, following the pattern I showed on the whiteboard:

```py
from polls.models import Question, Choice
num_questions = ... # will _eventually_ be 10_000, but start with something small, like 2
for _ in range(num_questions):
    question = Question.objects.create(...)
    num_choices = ...  # will _eventually_ be a random number 1 - 10, but start with something small, like 1
    for _ in range(num_choices):
        choice = Choice.objects.create(...)
```

`...` indicates places you will need to fill in code. Once you have this working for small numbers of Questions, you can increase `num_questions` to make larger numbers at once.

This task will be considered done once there are more than 10,000 Questions in the database that have 1-10 Choices associated with them

To open the shell:

```sh
./manage.py shell
# Type or paste your code in and execute it
```

To see what fields are required to create a `Question` or `Choice`, you can look at `polls/models.py`, or execute the following directly in the Django shell:

```py
# e.g. for Question:
Question?
```

**Comment by sofiarobertson** [comment]
In [6]: Question.objects.count()
Out[6]: 13933
