### ISSUE TITLE
Change question list to be a question table

### ISSUE THREAD

**Issue by tchamberlin** [GreenBankObservatory/summer_onboarding_2024#7]
Currently poll questions are displayed as a simple list. This limits the amount of information we can display.

To address this, convert the current `<ul>` structure into a `<table>`. The table should have four columns:

1. The question text
2. The publication date
3. The total number of choices
4. The total number of votes (across all choices for a given row)

**Comment by tchamberlin** [comment]
Additional requirement: table should be ordered by number of votes, in descending order

**Comment by sofiarobertson** [comment]
committed!
